### ISSUE TITLE
Don't depend on full zendframework package?

### ISSUE THREAD

**Issue by jaydiablo** [akrabat/AkrabatSession#4]
Rob, curious your thoughts on this, I'm using this module in a ZF2 project that is using ZF2 2.5+ and was trying to just define the ZF2 packages the project is using, however, this session module has "zendframework/zendframework" in the composer "require" section, so all of the ZF2 packages are pulled down.

Could just the modules this module depends on be put in the require block (and perhaps move zendframework/zendframework to require-dev if needed for tests)?

Happy to take a look at what packages those would be if you think that's an acceptable approach.

**Comment by akrabat** [comment]
Yes, it should just be the specific packages required. `zendframework/zendframework` was clearly laziness on my part!
